Feature/partial labels
deep-voice/soundbay pull request #19
Opened 2021-08-07 17:09 UTC by Z30G0D

partial labels

2021-08-08 19:40 UTC, noamzbr commented on src/conf/data/defaults.yaml
>    data_sample_rate: 44100
Don't think we want to commit changes to this file

2021-08-08 19:40 UTC, noamzbr commented on src/conf/data/partial_label.yaml
> +  val_dataset:
why for val partials aren't considered positive?

2021-08-08 19:40 UTC, noamzbr commented on src/conf/data/partial_label.yaml
> +    margin_ratio: 0.5
Sorry for silly question - but doesn't this behavior kinda overlap with partial positives? Can you remind us what the margin_ratio does?

2021-08-08 19:40 UTC, noamzbr commented on src/data.py
> +        self.metadata = self.metadata[self.metadata['call_length'] > self.seq_length]
don't we want >= ?

2021-08-14 17:35 UTC, Z30G0D commented
Following last week's conversation and silly changes...
As Noam mentioned,  I just changed margin_ratio a bit to include the label condition.

2021-08-15 12:40 UTC, mosheman5 commented on src/data.py
> +        if (self.mode == "train") and (label == 1):
important bugfix!

2021-08-15 12:41 UTC, mosheman5 commented on src/data.py
> +from copy import deepcopy
double import?

2021-08-15 12:41 UTC, mosheman5 commented on src/data.py
> +        # self.partial_positive = partial_positive
please delete if not needed

2021-08-15 12:41 UTC, mosheman5 commented on src/data.py
> +        assert (0 <= margin_ratio) and (1 >= margin_ratio)
me like assertions :)

2021-08-15 12:43 UTC, mosheman5 commented on src/conf/data/defaults.yaml
> +    slice_flag: true
why?

2021-08-15 12:44 UTC, mosheman5 requested changes
Improtant bugfix!
had tiny comments and potential bug in the data conf
other than that, lgtm

2021-08-20 07:46 UTC, merged